### ISSUE TITLE
[Bug] Continue button not showing up

### ISSUE THREAD

**Issue by 97kovacspeter** [martongyiran/CraftLogs#10]
**Describe the bug**
After generating a QR code the "Continue" button doesn't show up on my device and I have to close the app in order to get back to the main interface.

**To Reproduce**
1. Generate QR code 

**Expected behavior**
The QR code showing up and under that a Continue button should show up

**Screenshots**
![kép](https://user-images.githubusercontent.com/36060845/54314443-f873be00-45db-11e9-9dc9-02113fc5d696.png)

**Smartphone (please complete the following information):**
 - Device: Huawei P8 Lite
 - OS: Android 6.0
 - App version: 0.1.1 STG

**Comment by martongyiran** [comment]
Fixed in [[Bug] Continue button not showing up #10](https://github.com/martongyiran/CraftLogs/commit/0414f5a3bf926b77b63b2b8a0d685559976bf65c).
