### ISSUE TITLE
[Task] Valtozások lekövetése

### ISSUE THREAD

**Issue by martongyiran** [martongyiran/CraftLogs#64]
- Új tárgyak neve
- Új házak neve
- Új házak képe ( 9 / ház == 3 / kaszt)

A mostanit megtalálod itt a 299. sortól: https://github.com/martongyiran/CraftLogs/blob/develop/CraftLogs/CraftLogs/CraftLogs.BLL/Services/ItemGeneratorService.cs

**Comment by 97kovacspeter** [comment]
Csináltam egy pull requestet. Nem tudom, hogy a ház neveket elég-e ott átírni, vagy máshol is kell refaktorálni, de onnan már látod mik kellenek elvben.
